### PR TITLE
Add Message.fromEncoded and Message.fromEncodedArray specs

### PR DESCRIPTION
**Pull request by SimonWoolf**
as requested

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Nice, LGTM, @paddybyers?

**Comment by paddybyers** [comment]
> @paddybyers?

I would say that it decodes to the maximum extent possible, and leaves the residual encoding transforms in the `encoding` property of the returned message. Otherwise LGTM.

**Comment by tcard** [comment]
It's probably worth it to link this with other descriptions in the spec about how messages are encoded/decoded, so that we have it defined in a single place and to specify that what this does and what normal message enc/decoding does is the same.

**Comment by SimonWoolf** [comment]
Changes made as requested.

ably-js implementation: https://github.com/ably/ably-js/pull/344

**Pull request merged**
