### PR TITLE
New Diagrams

### PR DESCRIPTION
**Pull request by Srushtika**
New diagrams added in each section of the Reactor docs

### CODE REVIEW

**Comment by tomczoink** [comment]
Seems the failure is due to duplicates, same issue I faced in https://github.com/ably/docs/pull/361.

If you just replace your with the contents of https://github.com/ably/docs/blob/2383ed56bc7cd7972f5bf3d649d9afe2e447b2b1/content/client-lib-development-guide/features.textile with https://github.com/ably/docs/blob/71c82d6494353bb4d875135b457484dabb158ba0/content/client-lib-development-guide/features.textile you should be fine.

**Comment by Srushtika** [comment]
@tomczoink Thanks for the fix. The checks have passed now.
@mattheworiordan I've pushed the changes.

Thanks!

**Comment by mattheworiordan** [comment]
> If you just replace your with the contents of https://github.com/ably/docs/blob/2383ed56bc7cd7972f5bf3d649d9afe2e447b2b1/content/client-lib-development-guide/features.textile with https://github.com/ably/docs/blob/71c82d6494353bb4d875135b457484dabb158ba0/content/client-lib-development-guide/features.textile you should be fine.

For future reference, it would be better to `git cherry-pick` the commit that you had implemented instead of manually replicating the change.

**Comment by mattheworiordan** [comment]
Looks good to me, thanks 👍

**Pull request merged**
