### PR TITLE
spec: Support custom fallback hosts

### PR DESCRIPTION
**Pull request by mattheworiordan**
Customers have requested custom CNAME endpoints, yet if they do this currently, we cannot support fallback host functionality. This ensures the two are not mutually exclusive.

@SimonWoolf @paddybyers

### CODE REVIEW

**Comment by paddybyers** [comment]
Before we go into this is it with considering the simpler option of just having a way to modify the hard-coded defaults in the white-label solution?

**Comment by mattheworiordan** [comment]
> Before we go into this is it with considering the simpler option of just having a way to modify the hard-coded defaults in the white-label solution?

No, as I think this change is quite trivial and applies to all client libraries as opposed to just JS

**Comment by SimonWoolf** [comment]
:+1:

**Comment by paddybyers** [comment]
LGTM

**Pull request merged**
