### PR TITLE
[WEB-346] Add internal links on the website to pub-sub concept

### PR DESCRIPTION
**Pull request by Nosfheratu**
Explain why this change is being made.
----
Link to pub/sub concept page was not present in the content of the website

Explain how this is accomplished.
----
Added pub/sub links to content of the textile files

How do you manually test this?
----
Navigate to `/documentation/core-features/pubsub`
Navigate to `/tutorials/publish-subscribe`
Navigate to `/concepts/mqtt`
Navigate to `/documentation/mqtt`
Navigate to `/concepts/websub`

Look for `publish-subscribe` or `pub/sub` should to navigate to `/concepts/pub-sub`

Merge/Deploy Checklist
----

- [ ] It has been visually reviewed and accepted.
- [ ] It has been reviewed for code quality.
- [ ] It adds tests for the implemented features/fixed bugs.

Frontend Checklist
----

- [ ] Does this work on major browsers (Chrome, Firefox, Safari)?
- [ ] Does this work on mobile?
- [ ] Have you compared with the initial design / fit our [brand guidelines](https://brand.ably.com/)?
- [ ] Have you checked the code for accessibility issues?

### CODE REVIEW

**Comment by MarkWoulfeAbly** [comment]
@kennethkalmer we've taken a look at this from a format/functionality perspective and all seems good, can you please review the content?

**Comment by Nosfheratu** [comment]
> `https://www.ably.io/concepts/pub-sub` => `/concepts/pub-sub` so the links work on docs and on the main site :)

fixed

**Comment by MarkWoulfeAbly** [comment]
@Nosfheratu are you able to resolve these conflicts?

**Comment by Nosfheratu** [comment]
@MarkWoulfeAbly rebased and resolved conflicts

**Comment by MarkWoulfeAbly** [comment]
Thanks @Nosfheratu.

@kennethkalmer I just noticed that pub/sub as a core feature isn't currently a topic on the main website, should i make a ticket to get this added to the navigation?

**Comment by kavalerov** [comment]
I think the content of the navigation is something @remotekieran owns.

**Comment by remotekieran** [comment]
> I just noticed that pub/sub as a core feature isn't currently a topic on the main website, should i make a ticket to get this added to the navigation?

Which navigation are you talking about @MarkWoulfeAbly ?

**Comment by MarkWoulfeAbly** [comment]
@remotekieran the table of contents on the right-hand side of the page.

**Pull request merged**
