### PR TITLE
DOC-239 Change support links to new system

### PR DESCRIPTION
**Pull request by tbedford**
## Description

* A first go at replacing the support links from the old system to knowledge.ably.com.
* Also fixed a couple of minor errors such as a use of em-dash affecting links and an errant bracket.

* See also [DOC-239](https://ably.atlassian.net/browse/DOC-239)
* See also [DOC-249](https://ably.atlassian.net/browse/DOC-249) for known bad links (will fix in another PR, as they are not to do with this PR)

## Review

Needs a lot of testing!

### CODE REVIEW

**Comment by tbedford** [comment]
@markcoxsmith - I know you are busy but if you'd be able to dive in a check a few random link that would be great. Thanks.

**Comment by tbedford** [comment]
Looks like a couple of `*.md` files in `content/adapters` were missed.

**Review by kennethkalmer — COMMENTED** [review]
Loads of work in here! I just can't help but wonder why so many of the new URLs end with `-1`, and if we shouldn't rename them before this lands.

As far as checking every link goes, I'll lean on the external link checker in nanoc to very they're updated correctly :)

**Comment by tbedford** [comment]
@kennethkalmer - the support links now appear to be fixed. I will address the other broken links in another PR.

**Review by kennethkalmer — APPROVED** [review]
Looks good to me

**Pull request merged**
