### PR TITLE
RTN11c: Explicit connect should keep trying to recover connection state

### PR DESCRIPTION
**Pull request by tcard**
"Aborts the retry process" suggests that we should just abandon the
whole connection state recovery logic. In implementation terms, this
may be translated to breaking an actual loop with the associated
connection state TTL ([this happened recently in Go](https://github.com/ably/ably-go/pull/297)).

This doesn't make much sense, and it's really not useful. What should
happen instead is that the reconnection loop should skip the wait, and
attempt the next try right away.

### CODE REVIEW

**Comment by QuintinWillison** [comment]
I would appreciate it if @SimonWoolf could have a look at this one. This spec point was introduced in #112 and my concern is that if the nature of the spec point changes too much then how do we track which libraries are adhering to which version of the spec point. We have some internal guidance which we're building in Confluence but I don't think this particular type of change and when it's applicable has been discussed and decided anywhere canonical yet, as far as I'm aware, but I know Simon has an aptitude for remembering and/or finding these things... also way more historical context than me!

**Review by AndyNicks — APPROVED** [review]

**Review by owenpearson — APPROVED** [review]
LGTM, thanks

**Review by SimonWoolf — APPROVED** [review]
👍

>  I don't think this particular type of change and when it's applicable has been discussed and decided anywhere canonical yet

FWIW this seems to me like a clarification rather than a change of nature.

The old place that had guidance on different kinds of changes is https://github.com/ably/docs#branch-and-tag-scheme-for-features-spec in the readme.

The main mechanism for keeping track of this was nominally that the diff from one spec version to another, which client lib devs can use as the starting point for seeing what needs to be changed, is the old release tag to the new one - so that incorporates all changes since that tag, whether made to 1.2 after the 1.2 release, or 1.3-only made in the 1.3 integration branch. Each dev at the time then decides whether any particular change means something needs changing in their lib or not.

At least that was the idea at some point. The extent to which that was actually done in practice is unclear. And that picture is muddied further by The Spreadsheet, which might present its own view of which specs had substantive changes between versions.

Ultimately this has been a bit of a mess before, so up to Quintin to decide what he thinks is the right mechanism to use going forwards for how we should do spec changes.

**Comment by tcard** [comment]
> my concern is that if the nature of the spec point changes too much then how do we track which libraries are adhering to which version of the spec point

I wouldn't worry too much in this case, because the only consequence of doing it the "old" way is that we might believe we're DISCONNECTED for longer than we should. This is already possible if the server evicts the connection state for other reasons.

**Pull request merged**
