### PR TITLE
[ECO-4804] Update ably-js logging docs

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
## Description

Updates the logging documentation for ably-js:

- `log` was split into `logLevel` and `logHandler` (to conform with the spec) in ably-js v2.
- The global effect of setting logging configuration was removed in https://github.com/ably/ably-js/commit/5502a43 and will be released in 2.1.0.

Resolves https://github.com/ably/ably-js/issues/1766.

## Review

See the `logLevel` and `logHandler` documentation on [this page](https://ably-docs-eco-4804-upda-yxnwxj.herokuapp.com/docs/api/realtime-sdk?lang=javascript).

### CODE REVIEW

**Comment by lawrence-forooghian** [comment]
@m-hulbert I’m a bit confused about whether this can be merged or not. The documentation says "This API reference is for version 1.2 of the JavaScript SDK. Version 2.0 references are [available in TypeDoc.](https://ably.com/docs/sdk/js/v2.0/)", but the version dropdown says "v2.0". Can the v2-related changes in this PR be merged?

**Comment by jamienewcomb** [comment]
hey @lawrence-forooghian @m-hulbert 

this has been in review for over a month now. do we still need this? if not I suggest we just close the PR

**Comment by lawrence-forooghian** [comment]
I think it can't be merged right now since the documentation is still for ably-js v2. But that seems like something we need to address. Whether there's a plan for doing that in the near term, I don't know.

**Comment by m-hulbert** [comment]
This is dependent on an internal DR for API reference versioning at the moment. 

I will close it for now and make a reference to it in the JIRA I have for versioning the JS API references.

**Pull request closed without merging**
