### PR TITLE
Clarify that authUrl should not include querystring params

### PR DESCRIPTION
**Pull request by SimonWoolf**
cf https://github.com/ably/docs/issues/296

### CODE REVIEW

**Comment by mattheworiordan** [comment]
@SimonWoolf this is fine for now, but seems odd we have that constraint at all.  Why can't query params be used?  I think in Ruby I parse the URI and then reconstruct it.

**Comment by SimonWoolf** [comment]
> Why can't query params be used? I think in Ruby I parse the URI and then reconstruct it.

They could. We do something similar in ably-js. But not all client libs currently do that - in particular ably-java doesn't, which was the source of the original support issue. Hence https://github.com/ably/docs/issues/296 : "In future versions of the spec we might also want to standardise that behaviour. Not sure whether we should standardise on leniency or strictness".

I'd be fine with standardising on leniency, but until we do that, given that doesn't work in all client libs, we should tell people to use the way that's guaranteed to work, which is authParams. See the original support issue linked from #296, which was a customer using an authUrl that worked in ably-js but not in ably-java.

**Comment by mattheworiordan** [comment]
> I'd be fine with standardising on leniency

I wouldn't even say that's leniency, it's correctly. `authUrl` is a URL, yet we don't accept URLs in all libraries.  That's a bug IMHO, and not a lenient interpretation.

> we should tell people to use the way that's guaranteed to work

Agreed for now, but the issue should be updated to say a URL should in fact be allowed, of which a set of query string params may be included.

**Comment by tcard** [comment]
I vote for "leniency" (which I agree is "correctness", really) and mark `authParams` for deprecation in 2.0. Instead, `authBody` can be added for when `authMethod` is POST; or not support POST bodies at all (if you really want them you can use `authCallback`).

**Comment by mattheworiordan** [comment]
> and mark authParams for deprecation in 2.0. Instead, authBody can be added for when authMethod is POST; or not support POST bodies at all (if you really want them you can use authCallback).

Yes, perhaps, we also have `authHeaders`.  Seems odd we're going to all that effort to provide a mechanism to make HTTP requests when in reality, those requests are pretty useless in all envs other than browsers i.e. an immutable set of `authParams` is rarely what is needed, and instead those `authParams` (and other auth*) should be set at the time the request is being made.  So instead of building in all this complexity, `authCallback` is probably the preferred way we want customers to do this.

**Comment by SimonWoolf** [comment]
replaced by https://github.com/ably/docs/pull/297

**Pull request closed without merging**
