### PR TITLE
[WEB-3889] chore: remove old fanout, push, realtime compare pages

### PR DESCRIPTION
**Pull request by jamiehenson**
> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

https://ably.atlassian.net/browse/WEB-3889

In prod, these pages will redirect to `/compare/all`.

### CODE REVIEW

**Review by kennethkalmer — COMMENTED** [review]
@jamiehenson I searched through this branch and I cannot find any remaining files that reference the partials in `content/partials/compare`, so I'll delete them too and add them to this PR

**Comment by kennethkalmer** [comment]
@jamiehenson done, was simple enough to search for `compare/` in the `content` directory to see nothing is referencing these partials, and ditto for the images after removing the partials.

**Review by kennethkalmer — APPROVED** [review]

**Comment by jamiehenson** [comment]
Alrighty then

**Pull request merged**
