### PR TITLE
Protocol adaptors

### PR DESCRIPTION
**Pull request by mattheworiordan**
@SimonWoolf I made some updates to the translator docs in your repo, but then thought that it would be better to be in here and we can more easily link to code examples etc.

The only issue is the Pusher demo does not work.  Can you take a look?  Any feedback appreciated too.

FYI. The MD files are compiled to HTML files in the `output` folder so we can use that HTML in Freshdesk

### CODE REVIEW

**Comment by SimonWoolf** [comment]
LGTM. Added 5a992a3 to fix the pusher channel example (channel namespacing translation) (though haven't updated the jsbin hash, can't find the api key in the private repo)

**Comment by SimonWoolf** [comment]
Also added 7619fb9 to add some inline styles for output that looks decent when copied into freshdesk (which sets margins to 0 as it expects spacing to be done with wysiwyg-output `<p><br></p>` nonsense...)

**Comment by mattheworiordan** [comment]
@SimonWoolf, nice, it works now.  Should we update the docs to state that `public:` namespace is required if not private?

BTW. I've updated the private repo with the required `jsbin_config.yaml` file now

**Comment by mattheworiordan** [comment]
@SimonWoolf do you want to merge when ready and update the support site?

**Comment by SimonWoolf** [comment]
> Should we update the docs to state that public: namespace is required if not private?

It already does say that, in the 'channels' section. https://github.com/ably/docs/pull/139/files#diff-9bd3e2f604fda992561fb436e94dd147R66, plus an example in the table. Happy to tweak if you have a suggestion on making it clearer

I'll do the jsbin thing and merge when done, cheers

**Comment by mattheworiordan** [comment]
> Happy to tweak if you have a suggestion on making it clearer

Nope, that was me skim reading :)  Looks good on re-read

**Pull request merged**
