### PR TITLE
Added redirects, updated alt image, and added a new image.

### PR DESCRIPTION
**Pull request by ramiro-nd**
- Added redirects from 4 URLs of the tutorial that Google Analytic shows. (is the format of the URL ok? We don't need to include https://www.ably.io/? 
- Optimized the ALT attribute of the Data flow image
- Added a new image to showcase Syncfusion charts.

Let me know if it's all good

### CODE REVIEW

**Comment by tbedford** [comment]
The image looks kind of large. I will have a play and see if I can fix it - if not today then tomorrow first thing.

image

**Comment by tbedford** [comment]
@ramiro-nd - also the image is adjacent to the code that follows it. We really need a line of text before the following code block to break that up. If you can suggest a brief introductory text (a sentence) then I will add that before the code block. That is, we just need to say what the code block does so there is some context. Thanks.

**Comment by ramiro-nd** [comment]
> @ramiro-nd - also the image is adjacent to the code that follows it. We really need a line of text before the following code block to break that up. If you can suggest a brief introductory text (a sentence) then I will add that before the code block. That is, we just need to say what the code block does so there is some context. Thanks.

@tbedford that's a good point, maybe the image should go after the code then so it shows the result?

**Comment by tbedford** [comment]
> > @ramiro-nd - also the image is adjacent to the code that follows it. We really need a line of text before the following code block to break that up. If you can suggest a brief introductory text (a sentence) then I will add that before the code block. That is, we just need to say what the code block does so there is some context. Thanks.
> 
> @tbedford that's a good point, maybe the image should go after the code then so it shows the result?

Yes, I can try that, in which case I'll need to add some text on what the diagram is before we have the diagram.

**Review by tbedford — APPROVED** [review]
LGTM. Reviewed locally (as it's a fork) using the latest website release.

**Pull request merged**
