### PR TITLE
[WEB-580] Replace all diagrams and images in /documentation

### PR DESCRIPTION
**Pull request by Nosfheratu**
Why?

Our diagrams our inconsistent and we now have a new, consistent illusrated style.

### CODE REVIEW

**Comment by Nosfheratu** [comment]
@remotekieran some section of the google doc related to this ticket, requires to update Ably blog entries, so I was not able to do that or I couldn't to find where to change (in the case we are using  something like blogs CMS inside the website)

**Comment by remotekieran** [comment]
Amazing - if you're happy with the diagrams can we merge this with Master then @MarkWoulfeAbly ?

**Comment by MarkWoulfeAbly** [comment]
Sure feel free to squash and merge @Nosfheratu.

**Comment by Nosfheratu** [comment]
> Sure feel free to squash and merge @Nosfheratu.

@MarkWoulfeAbly 
I have squashed all commits but I was not able to merge into master because I am not authorized to merge

**Comment by kennethkalmer** [comment]
@Nosfheratu ping me on this repo to help with the merges, just like we do elsewhere 😉

**Pull request merged**
