### PR TITLE
docs: Java & Android - Ably installation update

### PR DESCRIPTION
**Pull request by piotrekinventica**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Thanks @piotrekinventica this looks good. However, I am not sure @paddybyers and @psolstice agreed that the plus in `compile 'io.ably:ably-android:0.8.+'` works.  Before I merge, @paddybyers can you confirm this is OK?

**Comment by paddybyers** [comment]
> Thanks @piotrekinventica this looks good. However, I am not sure @paddybyers and @psolstice  agreed that the plus in compile 'io.ably:ably-android:0.8.+' works. Before I merge, @paddybyers  can you confirm this is OK?

It does work afaik but its use is discouraged, and the last time we discussed it we thought that we agreed to use a fixed version in the tutorials. @psolstice?

**Comment by psolstice** [comment]
Yes, it works but gives warning in Android Studio. I think it's a safety precaution against broken library releases.

**Comment by mattheworiordan** [comment]
Well this is a huge waste of time to change again, so I am inclined to say in the tutorial itself we can reference specific versions so long as there is a note stating that the user should get the latest version with instructions and link on how to do that, and in the branches with demos that can be run locally (i.e. all PRs at https://github.com/ably/tutorials/pulls), unless they don't work, we should leave as is as changing that all back is a lot of unnecessary work.

@psolstice we need to get https://github.com/ably/docs/pull/213 completed and merged now so that @piotrekinventica can use that as a template for this PR i.e. he can update the version references and add the necessary comments about how to get the latest version.

**Comment by mattheworiordan** [comment]
@piotrekinventica please see the route  we've agreed on at https://github.com/ably/docs/pull/213.  Note that as your Android & Java tutorials work (in the tutorials repo), I don't suggest you change them. However please update this repo and the tutorial examples to use the new format and I'll merge this all in.

**Comment by piotrekinventica** [comment]
@mattheworiordan I've updated the docs, now all tutorials have the same gradle dependency just like in #213

**Comment by mattheworiordan** [comment]
Mind adding https://github.com/ably/docs/pull/213/commits/75f59014611e3612c043171d50f2a4681b54f03f as well and I'll merge

**Comment by piotrekinventica** [comment]
@mattheworiordan instructions added

**Comment by mattheworiordan** [comment]
Thanks, this is all merged in

**Pull request closed without merging**
