### PR TITLE
[EDX-42] GUI colours

### PR DESCRIPTION
**Pull request by MymmiJ**
> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

Updates GUI colors to be in line with migration guide: https://www.figma.com/file/4KdtIEGY2BfZPq5tT1u6D3/Migration-Guide?node-id=0%3A410

* [Jira ticket](https://ably.atlassian.net/browse/EDX-42).

## Review

Ensure that new colors match guidelines provided by Lenka here:

"I raised this with Jamie and he decided to change the colour of the hyperlinks to our GUI Blue Default and display the underline only on hover. I already updated the Migration Guide. You can use our Active Blue, Focus Blue etc. for other states."

Ensure references to the pre-migration GUI colors are no longer used in the code base.

### CODE REVIEW

**Review by DuncanEdwards — CHANGES_REQUESTED** [review]
Can we please:
- Make the mouse hover the correct blue and a thinner design (as per Figma)
- Make A.js and Pre.js TypeScript please

**Comment by DuncanEdwards** [comment]
image
I got the branch and this is what I get on localhost. Am I doing something wrong?

**Comment by DuncanEdwards** [comment]
> > * Make the mouse hover the correct blue and a thinner design (as per Figma)> * Make A.js and Pre.js TypeScript please
> 
> TypeScript sounds good, where are you seeing the thinner design? This is the only source of truth I know of for the design & it just describes colours: https://www.figma.com/file/4KdtIEGY2BfZPq5tT1u6D3/Migration-Guide?node-id=0%3A410 The hover is VERY similar to the regular blue, but it should be correct: Screenshot 2022-04-12 at 14 25 38 https://github.com/ably/ably-ui/blob/main/src/core/styles/properties.css ` --color-gui-hover: #0867c4;` vs
> 
> ```
> Hex
> #0867C4
> ```

It is the text-decoration color not being orange that is the issue here

**Comment by MymmiJ** [comment]
> > > * Make the mouse hover the correct blue and a thinner design (as per Figma)> * Make A.js and Pre.js TypeScript please
> > 
> > 
> > TypeScript sounds good, where are you seeing the thinner design? This is the only source of truth I know of for the design & it just describes colours: https://www.figma.com/file/4KdtIEGY2BfZPq5tT1u6D3/Migration-Guide?node-id=0%3A410 The hover is VERY similar to the regular blue, but it should be correct: Screenshot 2022-04-12 at 14 25 38 https://github.com/ably/ably-ui/blob/main/src/core/styles/properties.css ` --color-gui-hover: #0867c4;` vs
> > ```
> > Hex
> > #0867C4
> > ```
> 
> It is the fact that the text-decoration color should not be orange that is the issue here

Oh, I didn't get that from the description cheers. Will update that now.

**Review by DuncanEdwards — APPROVED** [review]

**Review by DuncanEdwards — APPROVED** [review]

**Pull request merged**
