### PR TITLE
Tutorials pages unexpected content and dp header images

### PR DESCRIPTION
**Pull request by dpiatek**
This PR fixes:

https://ably.atlassian.net/browse/WEB-285

- this was due to the deletion of the image in the website repo in commit https://github.com/ably/website/commit/faf88c249f4474e9e38532a5df900159df962bad
- moving the images here, will require a small code change in the website repo (see PR WIP)
- added images were changed to JPEG's so they are smaller in size

https://ably.atlassian.net/browse/WEB-286

- this issue was caused by irregular indentation on the articles in question which broke the parsing
- some tutorials had empty "Overview" sections due to starting the article with a heading which generates a step; these heading were removed
- removed jump-tos on articles where these were generated client-side

### CODE REVIEW

**Comment by fliptopbox** [comment]
2020-04-15-110749_1027x582_scrot
- [ ] The code blocks with long lines are overflowing

**Comment by fliptopbox** [comment]
@jamienewcomb @dpiatek see screenshot above. If bug this is out-of-scope I am happy to approve the PR. Please confirm. Thx

**Comment by dpiatek** [comment]
happy to fix that @fliptopbox

**Comment by jamienewcomb** [comment]
@dpiatek @fliptopbox Seems like the issue already [exists](https://ably-docs-tutorials-cop-bj8wd9.herokuapp.com/tutorials/channel-occupancy-events/). Will leave this with you guys to decide if this should be fixed as part of this PR

**Comment by dpiatek** [comment]
Yours looks very different to mine @fliptopbox 

Screenshot 2020-04-15 at 14 21 44

Any chance you have and adblock or similar on?

**Comment by dpiatek** [comment]
@fliptopbox sorry for the noise, just realised you were looking at docs.ably.io (while my screenshot is from /documentation) forgot I need to look at two different websites for this 🥈

**Comment by fliptopbox** [comment]
Chrome: Version 81.0.4044.92 (Official Build) (64-bit) - no ad blocker
Firefox: 75.0 (64-bit) no-adblocker
Brave: Version 1.7.90 Chromium: 80.0.3987.163 (Official Build) - has add blocking
Safari: unable to check

I get the same symptom across all three.

**Comment by Srushtika** [comment]
> @dpiatek @fliptopbox Seems like the issue already [exists](https://ably-docs-tutorials-cop-bj8wd9.herokuapp.com/tutorials/channel-occupancy-events/). Will leave this with you guys to decide if this should be fixed as part of this PR

@dpiatek @jamienewcomb @fliptopbox 
Re this bug, I think this can be resolved in another PR please as the current PR fixes urgent issues and that broken code box is only in the docs preview site - something we use internally only.

**Comment by dpiatek** [comment]
hey @Srushtika @fliptopbox thanks for the approvals. Can one of you give me access to merge or merge this PR please :) ?

**Comment by Srushtika** [comment]
@tomczoink are you able to give @dpiatek permissions please? I can change settings for other collaborators.

**Pull request merged**
