### PR TITLE
DOC-214: Remove reference to services that aren't supported

### PR DESCRIPTION
**Pull request by m-hulbert**
This PR removes reference to services that aren't supported and where customers were being asked to get in touch.

The page that was changed by this can be viewed [here](https://ably-docs-pr-1125.herokuapp.com/general/firehose/).

### CODE REVIEW

**Comment by ginotoro** [comment]
The image shows Kafka. Can we change that @m-hulbert ? Check with Kieran

**Comment by m-hulbert** [comment]
> The image shows Kafka. Can we change that @m-hulbert ? Check with Kieran

Good spot. I'll double check with Kieran and get a new image from design.

**Review by marklewin — APPROVED** [review]
Looks OK to me @m-hulbert !

**Review by tbedford — APPROVED** [review]

**Comment by m-hulbert** [comment]
I've updated that image if you're happy with the rest @ginotoro

**Review by ginotoro — APPROVED** [review]
LGTM

**Pull request merged**
