### PR TITLE
Correct env default from "" to null

### PR DESCRIPTION
**Pull request by tomczoink**
For #444

### CODE REVIEW

**Comment by tomczoink** [comment]
@mattheworiordan changed it to have specifics for each lib based off of example you provided. Seem correct?

**Comment by mattheworiordan** [comment]
@tomczoink (and @Srushtika so that you know), please always check how the page renders before you commit changes to the documentation pages.  The Textile formatting is complicated and what you implement may not render as you expect.  See below from this recent change:

screen_capture 2018-07-04_10-17-35_am

**Comment by tomczoink** [comment]
Not merged accidentally closed it @mattheworiordan. Formatting should all be fine now.

**Comment by mattheworiordan** [comment]
@tomczoink does CSharp not support `null` or an equivalent as opposed to an empty string?

**Comment by tomczoink** [comment]
You're right, fixed @mattheworiordan. Good to merge?

**Pull request merged**
