### PR TITLE
[WEB-3034] Remove faq links in white label

### PR DESCRIPTION
**Pull request by Nosfheratu**
## Description

https://ably.atlassian.net/browse/WEB-3034

### CODE REVIEW

**Comment by Nosfheratu** [comment]
@aralovelace y create this branch from `nanoc-toolchain` and it still failing the heroku build/deploy, not sure why, i double checked the app can be executed locally btw

image

**Comment by MymmiJ** [comment]
> @aralovelace y create this branch from `nanoc-toolchain` and it still failing the heroku build/deploy, not sure why, i double checked the app can be executed locally btw
> 

@Nosfheratu Please can you pull from nanoc-toolchain?

**Comment by Nosfheratu** [comment]
> @Nosfheratu Please can you pull from nanoc-toolchain?

@MymmiJ  done!

**Review by MymmiJ — APPROVED** [review]
LGTM!

**Pull request merged**
