### PR TITLE
[FEA-885] change term to state persistence

### PR DESCRIPTION
**Pull request by Nosfheratu**
Explain why this change is being made.
----
In the Channel rules page change the term “last message persisted” to state persistence

Explain how this is accomplished.
----
copy was changed

How do you manually test this?
----
Navigate to http://ably-docs-pr-1042.herokuapp.com/general/channel-rules-namespaces/

copy of the second element of the list should start with  'State persistence'

Merge/Deploy Checklist
----

- [x] It has been visually reviewed and accepted.
- [ ] It has been reviewed for code quality.
- [ ] It adds tests for the implemented features/fixed bugs.

Frontend Checklist
----

- [ ] Does this work on major browsers (Chrome, Firefox, Safari)?
- [ ] Does this work on mobile?
- [ ] Have you compared with the initial design / fit our [brand guidelines](https://brand.ably.com/)?
- [ ] Have you checked the code for accessibility issues?

### CODE REVIEW

**Comment by Nosfheratu** [comment]
hey @ginotoro check this PR related to [FEA-885](https://ably.atlassian.net/browse/FEA-885)

**Review by kennethkalmer — APPROVED** [review]

**Comment by tbedford** [comment]
Does this not also affect "Persist last message" in `channel-params.textile`, and `rewind.textile`? Also, in the Dashboard UI we still refer to "Persist last message", and "Persist all messages".

**Comment by Nosfheratu** [comment]
> Does this not also affect "Persist last message" in `channel-params.textile`, and `rewind.textile`? Also, in the Dashboard UI we still refer to "Persist last message", and "Persist all messages".

This case in specific only affect to `channel-rules-namespace` page with that specific copy replacement 

affected views:

- content/general/channel-rules-namespaces.textile
- content/realtime/channels.textile
- content/realtime/versions/v1.0/channels.textile
- content/realtime/versions/v1.1/channels.textile
- content/realtime/versions/v0.8/channels.textile
- content/realtime/versions/v0.8/messages.textile
- content/rest/channels.textile
- content/rest/versions/v1.0/channels.textile
- content/rest/versions/v1.1/channels.textile
- content/rest/versions/v0.8/channels.textile
- content/rest/versions/v0.8/messages.textile

**Comment by tbedford** [comment]
Sorry, what I meant was do we need to change the text "Persist last message" as it does appear in `channel-params.textile`, and `rewind.textile` as well, and the partial you modified already does not affect those files?

**Comment by Nosfheratu** [comment]
> Sorry, what I meant was do we need to change the text "Persist last message" as it does appear in `channel-params.textile`, and `rewind.textile` as well, and the partial you modified already does not affect those files?

@tbedford I am not sure, need to check

**Comment by ginotoro** [comment]
> > Sorry, what I meant was do we need to change the text "Persist last message" as it does appear in `channel-params.textile`, and `rewind.textile` as well, and the partial you modified already does not affect those files?
> 
> @tbedford I am not sure, need to check

Any update on this? I'll wait before I approve.

**Comment by Nosfheratu** [comment]
> Any update on this? I'll wait before I approve.

@ginotoro I have addressed your request...

**Review by tbedford — APPROVED** [review]

**Pull request merged**
