### PR TITLE
Consolidate functions and webhooks documentation between versions

### PR DESCRIPTION
**Pull request by MarkWoulfeAbly**
This PR addresses #893, that is, aimed at resolving the disconnect between the reactor integration rules documentation before and after V1.0

### CODE REVIEW

**Comment by MarkWoulfeAbly** [comment]
Hey @SimonWoolf do you think it is worth also adding a note on the cloudflare, ifttt and zapier pages that they also work with v1.0? Is there any difference when using them with v1.1 and v1.0?

**Comment by SimonWoolf** [comment]
> Hey @SimonWoolf do you think it is worth also adding a note on the cloudflare, ifttt and zapier pages that they also work with v1.0? Is there any difference when using them with v1.1 and v1.0?

The version makes literally no difference to any rule types ever, with one single exception, which is the presence action for batched webhook rules in 0.8 vs higher.

Honestly, I think what we do now — that is, when we restructured and rewrote the rule docs, having that apply only to v1.1/1.2 and keeping the old structure for v0.8/v1.0 — is horribly confusing.

Due to the different page structures a customer can't change the version in the dropdown to manually compare them, so we're reduced to this kludge of editing the body copy to mention the older or newer versions. But even with that, what are we expecting them to do, read the two differently-structured different sets of rule documentations to compare them and get a useful answer about what changed? That just doesn't work IMO.

My suggestion would be: just get rid of the version dropdown and older versions for rule docs. A version dropdown makes sense for client library API docs, but I don't think it does for rules. Instead just have a changelog, or version table or something. (With all of one single item big).

(Also restore the crucial information about how to decode messages received over rules, which got stripped out during the restructure and not been reinstated yet - https://github.com/ably/docs/issues/865 )

**Comment by MarkWoulfeAbly** [comment]
So i dont know why force pushing a reset causes this to close but ill be opening a separate PR with the new structure.

**Comment by MarkWoulfeAbly** [comment]
@SimonWoolf I have reverted the previous changes and copied across the events and function pages from v1.1 to v1.0.

Before working on a similar commit for v0.8 I just want to clarify, beyond the presence action for batched webhook rules, which i can update the copy for, are all the other pages good to just copy over as is?

**Comment by SimonWoolf** [comment]
> beyond the presence action for batched webhook rules, which i can update the copy for, are all the other pages good to just copy over as is?

yes. (I guess that means you decided to keep the dropdown?)

(relatedly, might be a good time to fix https://github.com/ably/docs/issues/865 while you're doing webhook docs?)

**Comment by mattheworiordan** [comment]
@MarkWoulfeAbly please can you refer to https://ably.atlassian.net/wiki/spaces/ENG/pages/312377505/Git-PR-best-practice as this PR has no comment or description.  Everyone needs this to have context of what they're reviewing.

Can you please explain what you're trying to achieve with this PR?  I am not clear from the single commit.

**Comment by MarkWoulfeAbly** [comment]
> yes. (I guess that means you decided to keep the dropdown?)
> 
> (relatedly, might be a good time to fix #865 while you're doing webhook docs?)

@SimonWoolf Yes I will be keeping the API dropdown for now to keep consistency with the rest of our documentation. I will also be addressing #865 but will do that in a separate PR after this one lands.

@mattheworiordan It seems that the Issue this PR addresses has been unlinked for some reason, I will update the description.

**Comment by MarkWoulfeAbly** [comment]
So to recap the changes:

1. WebHooks (v0.8) and Functions (v0.8,1.0) have been removed
2. Events(v0.8) examples have been updated to show presence.action as a string and not an enum.
3.

**Pull request merged**
