### PR TITLE
Add Swift and Obj-C versions of the docs.

### PR DESCRIPTION
**Pull request by tcard**
There's also a fix in the IDL. `RealtimePresence.get` should produce a `[PresenceMessage]`, not a `PaginatedResult<PresenceMessage>`. This is done wrong in iOS (ably/ably-ios#271).

### CODE REVIEW

**Comment by mattheworiordan** [comment]
This is just awesome, nice work @tcard :+1:

**Comment by tcard** [comment]
No problem, sorry for all the silly errors. Should've reviewed before more thoroughly.

**Comment by mattheworiordan** [comment]
@tcard I've pushed a few fixes. But honestly, I am so impressed, didn't think it was going to be easy to approach it all, you're a lifesaver, thanks!

Feel free to rebase and merge if you're happy with my fixups

**Comment by tcard** [comment]
:+1:

**Pull request merged**
