### PR TITLE
[WEB-64] created 4 new textile articles w respective PNGs

### PR DESCRIPTION
**Pull request by fliptopbox**
* Part **two** of two (the 4 article pages for **docs** repo)
* _the index page will appear in the PR for the *website* repo_
* (website repo PR) https://github.com/ably/website/pull/3015

### How to review this PR

* `cd docs/`
* `bundle exec nanoc compile`
* `bundle exec nanoc view -p 4000`
* open browser to: http://localhost:4000

### Notes

* Known issues in the PR:
- none of the articles contain the author metadata blocks (unavailable)
- missing images have been substituted with 1x1 transparent shims

### images that require replacement graphics

**HTTP/2**

- http-2-anatomy-2.png 
- http-2-anatomy.png
- http-2-flow-control.png
- http-2-frame-diagram.png
- http-2-message-diagram.png
- http-2-stream-diagram.png

**HTTP/3**
- http-3-protocol-stack.png
- http-3-tcp-handshake.png
- http-3-tcp-hol-blocking.png 
- http-3-tcp-stream.png
- http-3-tcp-vs-quic.png

### Quality control

* [ ] Does this work on major browsers (Chrome, Firefox, Safari)?
* [X] Does this work on mobile?
* [X] Have you compared with the initial design / fit our [brand guidelines](https://brand.ably.io/)?
* [ ] Have you created tests for the implemented features?
* [X] Have you structured your code in a consistent manner (spacing, newlines, folder structures, appropriately sized images, DRY'd up code, etc)?

### CODE REVIEW

**Comment by DominikElmiger** [comment]
Corrections

[1) Pub/Sub](https://ably-docs-staging-pr-812.herokuapp.com/concepts/pub-sub/)
Image missing after header <Publish-Subscribe at Scale>
Links not added

2) HTTP2
One link missing (http archive)

3) HTTP3
good

4) Web-Sub
good

**Comment by mattheworiordan** [comment]
FYI. In order to review a PR site should be built and launched automatically... so no need to run locally to review. See the links above, seems to have worked as expected

**Comment by fliptopbox** [comment]
@DominikElmiger  fixed missing links (Pub/Sub & HTTP/2)  and added missing image.

**Comment by jamienewcomb** [comment]
@mattheworiordan @DominikElmiger We are missing images for HTTP/2/HTTP/3. Bruce has made this simple for us to add these at a later point but do we want to publish these with missing images to begin with? We are also missing meta data for the author information on these articles so same question here. If you can point us in the direction of the missing images/author information then we can add

But for now -  let us know if you are happy for us to proceed with the missing images/information or if we should wait, thanks

**Comment by jamienewcomb** [comment]
@fliptopbox - Dom has suggested we proceed with the following articles for now as we still don't have images for the other two

- Publish/Subscribe
- WebSub

Would it be possible to split this PR so we only merge those articles for now?

Thanks
Jamie

**Comment by fliptopbox** [comment]
@jamienewcomb  just pushed the update to remove the 2 http articles

**Pull request merged**
