### PR TITLE
Add code snippet and information for `authCallback`

### PR DESCRIPTION
**Pull request by ben-xD**
Just adding some notes about using `authCallback`, since it didn't exist before. 

**TODO:** 
- [ ] ~~create new JSBin~~
- [ ] ~~Fix code snippet formatting~~

### CODE REVIEW

**Comment by tbedford** [comment]
Notes: minor tidy to text with additional markup. We had content/code/authentication/auth-callback.code, so I linked to that. Tested the Try it Out and the code sample seemed to work fine. 
image

**Comment by ben-xD** [comment]
Thanks @tbedford , it looks good, so I don't think there's anything else on my side

**Comment by tbedford** [comment]
@marklewin - I only had a quick look. Would you be able to take a look please? Thanks.

**Review by tbedford — APPROVED** [review]

**Review by marklewin — APPROVED** [review]
LGTM!

**Comment by ben-xD** [comment]
Cool, I'm not able to merge it because `The base branch restricts merging to authorized users`. Feel free to do it, thanks

**Pull request merged**
