### PR TITLE
[WEB-3034] Remove faq links in white label

### PR DESCRIPTION
**Pull request by Nosfheratu**
## Description

https://ably.atlassian.net/browse/WEB-3034

## Review

Instructions on how to review the PR. 

- compare/ably-vs-pusher
- compare/ably-vs-pubnub

### CODE REVIEW

**Review by MymmiJ — CHANGES_REQUESTED** [review]
This change seems fine, does it need to be branched from the Nanoc toolchain branch (https://github.com/ably/docs/tree/nanoc-toolchain), merged in there, and then old deploy process followed though? @Nosfheratu @aralovelace 
Cc @dpiatek Compare pages going through the Nanoc toolchain could be a point of friction for developers if I am correct about this being the right process, which I think I am. I'd suggest I document the process for deploying compare pages if this is the correct way to deal with them.

**Comment by aralovelace** [comment]
@MymmiJ 
I am not sure about this yet, I was trying to test the changes from @Nosfheratu but now it seems like I cant see any table - https://ably-docs-web-3034-remo-sw1mtz.herokuapp.com/docs/compare/ably-vs-pusher

**Comment by MymmiJ** [comment]
> @MymmiJ I am not sure about this yet, I was trying to test the changes from @Nosfheratu but now it seems like I cant see any table - https://ably-docs-web-3034-remo-sw1mtz.herokuapp.com/docs/compare/ably-vs-pusher

It won't show on the preview apps, these pages are Ruby & can only be rendered by the nanoc-toolchain branch; it almost certainly needs to be merged into that branch and to follow an older process for deploying changes.

**Comment by aralovelace** [comment]
@MymmiJ  okay thanks

@Nosfheratu  can you update this files from the `nanoc-toolchain` branch please maybe close this PR and create new PR

**Comment by Nosfheratu** [comment]
> @MymmiJ okay thanks
> 
> @Nosfheratu can you update this files from the `nanoc-toolchain` branch please maybe close this PR and create new PR

@aralovelace sure!

**Comment by Nosfheratu** [comment]
@aralovelace I just updated this PR and only include the change to `compare.yml`, **data.yml is not necessary** since pubnub and pusher read the same file

**Comment by Nosfheratu** [comment]
@aralovelace  I also changed the base branch for this PR, so its not necessary create a new one

**Comment by Nosfheratu** [comment]
> I think you needed to branch it from Nanoc toolchain as what Jimmy said

@aralovelace thats strange, branched from nanoc toolchain using the same branch name and force push the branch

image

**Comment by Nosfheratu** [comment]
@aralovelace not sure what happened with that deploy, however it seems the gem only need to be updated, and to see the change it only requires the branch is merged into nanoc toolchain branch, i tested locally changing the branch and it worked!

image

**Comment by aralovelace** [comment]
@Nosfheratu   but we need to make sure it works in the App Review before approving and merging this PR.
The reason why I suggested to create a new PR so that it will build a new heroku app review and it might fix the issue.

**Pull request closed without merging**
