### PR TITLE
RTN15h: token errors, when the library can renew, result in DISCONNEC…

### PR DESCRIPTION
**Pull request by paddybyers**
Fixes: https://github.com/ably/docs/issues/429

### CODE REVIEW

**Comment by SimonWoolf** [comment]
> integration-spec-1-1

(btw, we already have `master-1-1` acting as an integration branch for the 1.1 spec, why do we have `integration-spec-1-1` too? neither is a parent of the other)

**Comment by paddybyers** [comment]
> (btw, we already have master-1-1 acting as an integration branch for the 1.1 spec, why do we have integration-spec-1-1 too? neither is a parent of the other)

`integration-spec-1-1` was created as the authoritative integration branch because `master-1-1` had things in it that weren't actually spec changes (eg https://github.com/ably/docs/commit/b276d760702f1e3db01fca2311d0f732e260828e). I do remember a discussion about that with Matt at the time but I can't remember if there was also a plan to merge those non-spec commits.

However, we should tidy things up and decide if there's anything in there that's got lost and needs to be dealt with.

**Comment by mattheworiordan** [comment]
> integration-spec-1-1 was created as the authoritative integration branch because master-1-1 had things in it that weren't actually spec changes (eg b276d76).

@paddybyers the only reason it has non spec 1.1 commits is because master-1-1 has not been rebased, see https://github.com/ably/docs/commit/2d11e3eee595d684f8028d196660a0b7dee50c6f#diff-04c6e90faac2675aa89e2176d2eec7d8 which is on master.

I think we should rebase and not have two separate branches for the same thing.

**Comment by paddybyers** [comment]
> I think we should rebase and not have two separate branches for the same thing.

I think that means rebase `integration-spec-1-1`, delete `master-1-1` and ensure that all non-spec commits are in `master`. You're ok for me to do that?

**Comment by mattheworiordan** [comment]
Well I personally would have simply rebased `master-1-1` given it's used by the [running 1.1 PR](https://github.com/ably/docs/pull/258) we've had open for a very long time.

**Comment by paddybyers** [comment]
Closing (superseded by https://github.com/ably/docs/pull/447)

**Pull request closed without merging**
