### PR TITLE
Tweak cipherparams description, add getDefaultParams

### PR DESCRIPTION
**Pull request by SimonWoolf**
discussion in https://github.com/ably/ably-js/pull/120

### CODE REVIEW

**Comment by mattheworiordan** [comment]
:+1: merge away unless @paddybyers objects

**Comment by paddybyers** [comment]
The default `keyLength` is not 128; each algorithm has its own range of possible values and default. I suggest:

    @(TZ2b)@ @keyLength@ integer - An integer, from an algorithm-dependent range of possible values. If unspecified, an algorithm-dependent default is used. For AES the allowed values at least include 128 and 256, with a default of 128.

**Comment by paddybyers** [comment]
Other than that, lgtm

**Comment by SimonWoolf** [comment]
Merged with Paddy's change

**Pull request merged**
