### PR TITLE
Spec: add requirements for Auth.currentTokenDetails

### PR DESCRIPTION
**Pull request by paddybyers**
See https://github.com/ably/docs/issues/671

### CODE REVIEW

**Comment by paddybyers** [comment]
> (I'd prefer `auth.tokenDetails` over `auth.currentTokenDetails` just because then ably-js is already compliant, if renaming it would need to support both to avoid a breaking change. But shrug)

@mattheworiordan any opinion either way?

**Comment by mattheworiordan** [comment]
I would be happy with `tokenDetails` as opposed to `currentTokenDetails`.  `current` generally is probably unnecessary in most cases across the lib.

**Comment by mattheworiordan** [comment]
Should we update this PR so it can be merged?  If we do merge it, are we expecting all client libs to implement, or is this going to form part of a new spec version?  If the latter, this PR is based on `master` which is wrong.

**Comment by mattheworiordan** [comment]
Ping @paddybyers

**Comment by SimonWoolf** [comment]
I updated the pr. no strong opinion on whether it should be modifying the current version or against a new version, other than a general inclination to default to modifing the current version given a change which doesn't break compatibility given we have no idea if/when we might want to go to 1.2

**Pull request merged**
