### PR TITLE
chore: update wordings to improve readability

### PR DESCRIPTION
**Pull request by clarencepenz**
## Description
Fixed a couple of typos in the docs

### CODE REVIEW

**Comment by GregHolmes** [comment]
Hi @clarencepenz,

Thank you for your PR, we always appreciate when people assist us on improving our documentation.

Before I can merge this, could I please ask you to rebase your branch from main, and also fix the merge conflict?

Thanks
Greg

**Comment by clarencepenz** [comment]
Hey @GregHolmes! It's always a pleasure. I have resolved the conflicts.

**Review by GregHolmes — APPROVED** [review]

**Comment by GregHolmes** [comment]
All merged. Thank you for fixing those typos.

**Comment by clarencepenz** [comment]
Always a pleasure @GregHolmes

**Pull request merged**
