### PR TITLE
[FEA-547] Change jsbin domain from ably.io to ably.com (AUGUST)

### PR DESCRIPTION
**Pull request by dpflucas**
Change jsbin domain from jsbin.ably.io to jsbin.ably.com.

## Review

* [Review app](https://ably-docs-pr-925.herokuapp.com/)

### CODE REVIEW

**Review by tomczoink — APPROVED** [review]

**Comment by tbedford** [comment]
@kennethkalmer - this was green ticked, but has the blocked label. However, as it's approved unless there are any objections I will merge this.

**Comment by tbedford** [comment]
Blocked for now. "DNS and other upstream things for jsbin"

**Comment by kennethkalmer** [comment]
@tbedford I rebased this and I believe this is ready to go live properly, here and on the website.

**Review by tbedford — APPROVED** [review]

**Comment by tbedford** [comment]
Try it out still seems to work.

**Comment by tbedford** [comment]
@kennethkalmer - it seems to work - is there anything specific I should test for in the review app?

**Pull request merged**
