### PR TITLE
[EDU-189] - Improve Token Revocation description over enforcement times

### PR DESCRIPTION
**Pull request by GregHolmes**
## Description

Token Revocation was confusing developers over the timeline of the revocation enforcement. This PR adds an improvement to the description to reduce the confusion, in stating that the revocation enforcement is immediate unless `allowReauthMargin` is defined as true in the request. This would delay the enforcement by 30 seconds to allow the client to request a new token without disruption to service.

* [Jira ticket](https://ably.atlassian.net/browse/EDU-189).

## Review

Instructions on how to review the PR. 

* [Page to review](https://ably-docs-edu-189-make--tg4am4.herokuapp.com/docs/auth/revocation)

### CODE REVIEW

**Review by m-hulbert — CHANGES_REQUESTED** [review]
Looks good (and thanks for fixing the image and `keyName`).

One small comment - I think we should state the default in the opening paragraph so that they don't need to scroll to a property to find that out.

**Comment by GregHolmes** [comment]
> Looks good (and thanks for fixing the image and `keyName`).
> 
> One small comment - I think we should state the default in the opening paragraph so that they don't need to scroll to a property to find that out.

https://github.com/ably/docs/pull/2037/commits/26b24ef66997e5e4832e77b0f889c50064738226

@m-hulbert Could you please let me know what you think of this? 

Thank you.

**Review by franrob-projects — CHANGES_REQUESTED** [review]
Just a typo fix! Otherwise LGTM 👍

**Review by franrob-projects — APPROVED** [review]
LGTM. Rebase time 🚀

**Review by m-hulbert — APPROVED** [review]
Good to go with a rebase 👍

**Pull request merged**
