### PR TITLE
Push notifications documentation improvements

### PR DESCRIPTION
**Pull request by ben-xD**
2 fixes:

- Typo: deliver instead of delivery
- Correction: Both realtime and rest have the `push` property.

### CODE REVIEW

**Review by marklewin — APPROVED** [review]
LGTM - thanks @ben-xD

**Comment by ben-xD** [comment]
I just realised I should use a relative path instead of the full URL, `https://ably.com/documentation/realtime/channels#properties`

**Review by tbedford — APPROVED** [review]

**Review by tbedford — CHANGES_REQUESTED** [review]
The links don't look correct to me:

1) You need a leading slash e.g. `"realtime":/realtime/channels#properties`
2) Both links point to realtime docs, I think the second one should point at Rest.

**Comment by ben-xD** [comment]
Thanks @tbedford , Im happy for you to merge it if you're happy

**Review by tbedford — APPROVED** [review]

**Pull request merged**
