### PR TITLE
change support domain from ably.io to ably.com

### PR DESCRIPTION
**Pull request by dpflucas**
Change any references from support.ably.io to support.ably.com

### CODE REVIEW

**Comment by MarkWoulfeAbly** [comment]
@dpflucas Looks like we're still on ably.io. Any idea when this change will be implemented?

**Comment by kennethkalmer** [comment]
I wonder if it would be possible to make the URL configurable in place like we did in the website repo

**Comment by kennethkalmer** [comment]
@dpflucas @MarkWoulfeAbly @tomczoink I rebased the work and updated several more files. If this looks good you folks can pull the trigger on this

**Comment by kennethkalmer** [comment]
⚠️ Urgh, ignore my "pull the trigger" comment ⚠️

**Pull request merged**
