### PR TITLE
Fix asset tracking connection code

### PR DESCRIPTION
**Pull request by tbedford**
## Description

Corrects the code example for connecting the publisher.

### CODE REVIEW

**Comment by tbedford** [comment]
@kavalerov - is this the error you spotted, or was there something else?

**Comment by tbedford** [comment]
@KacperKluka - could you take a look please? Thanks.

**Review by KacperKluka — APPROVED** [review]
Looks good :+1:

**Comment by tbedford** [comment]
Thanks @KacperKluka

**Pull request merged**
