### PR TITLE
Spec: add RTL5i (attached received while in the detaching state)

### PR DESCRIPTION
**Pull request by SimonWoolf**
As proposed by https://github.com/ably/docs/issues/1041, see that issue for more details and justification.

Already approved by Paddy in principle, this just implements it.

### CODE REVIEW

**Comment by SimonWoolf** [comment]
@QuintinWillison poke

**Comment by tbedford** [comment]
I've not looked into the specs much yet, but is this error "RTL5i has 1 duplicate(s)" something that needs to be looked into I wonder?

**Comment by SimonWoolf** [comment]
> I've not looked into the specs much yet, but is this error "RTL5i has 1 duplicate(s)" something that needs to be looked into I wonder?

Thanks, missed that, fixed

**Comment by paddybyers** [comment]
@QuintinWillison this spec change was implemented in ably-js but not the other libs. How do you intend to track this? Should issues be raised against the other libs?

**Comment by QuintinWillison** [comment]
Thanks, @paddybyers ... sorry for the glacial delay, but issues now created in the realtime-capable SDK repositories ☝️.

**Pull request merged**
